// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch a profile's executable with structured arguments.
 * The frontend is responsible for translating profile data into a safe
 * (program, args) pair — this command never invokes a shell.
 */
async launchProfileExecutable(executablePath: string, args: string[] | null, envVars: Partial<{ [key in string]: string }> | null, workingDir: string | null) : Promise<Result<ProcessOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_profile_executable", { executablePath, args, envVars, workingDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run a build step (e.g. `cmake --build`) for recompilation projects.
 * `working_dir` is required to keep build artifacts scoped to the project.
 */
async runBuildStep(workingDir: string, program: string, args: string[], envVars: Partial<{ [key in string]: string }> | null) : Promise<Result<ProcessOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_build_step", { workingDir, program, args, envVars }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Append a log entry for a profile, persisted as JSON.
 */
async saveLog(profileId: string, entry: ProfileLogEntry) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_log", { profileId, entry }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read all stored logs for a profile, newest first.
 */
async readLogs(profileId: string) : Promise<Result<ProfileLogEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_logs", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect all installed compatibility runtimes (Wine, Whisky, CrossOver, GPTK).
 */
async detectRuntimes() : Promise<RuntimeInfo[]> {
    return await TAURI_INVOKE("detect_runtimes");
},
/**
 * Detect all Wine/Whisky/CrossOver/GPTK bottles on the system.
 */
async detectBottles() : Promise<Bottle[]> {
    return await TAURI_INVOKE("detect_bottles");
},
/**
 * Get detailed metadata for a specific bottle by path.
 */
async getBottleMeta(bottlePath: string) : Promise<Result<Bottle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_bottle_meta", { bottlePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new Wine prefix at the given path.
 */
async createBottle(bottlePath: string, name: string, runtime: string) : Promise<Result<Bottle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_bottle", { bottlePath, name, runtime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a bottle's filesystem data.
 */
async deleteBottle(bottlePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_bottle", { bottlePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clone an existing bottle to a new location.
 * Preserves all files including the CiderDeck sidecar.
 */
async cloneBottle(sourcePath: string, destPath: string, name: string) : Promise<Result<Bottle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_bottle", { sourcePath, destPath, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Repair a bottle by running wineboot --update.
 */
async repairBottle(bottlePath: string, runtime: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("repair_bottle", { bottlePath, runtime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset a bottle back to a clean state.
 * Removes the Windows filesystem and registry, then reinitializes.
 * The CiderDeck sidecar (notes) is preserved across the reset.
 */
async resetBottle(bottlePath: string, name: string, runtime: string) : Promise<Result<Bottle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_bottle", { bottlePath, name, runtime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a bottle as a compressed tar archive (.tar.gz).
 * Returns the path of the created archive.
 */
async exportBottle(bottlePath: string, archivePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_bottle", { bottlePath, archivePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a bottle from a compressed tar archive (.tar.gz).
 */
async importBottle(archivePath: string, destPath: string, name: string) : Promise<Result<Bottle, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_bottle", { archivePath, destPath, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist user-provided notes for a bottle.
 */
async saveBottleNotes(bottlePath: string, notes: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_bottle_notes", { bottlePath, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGames() : Promise<Result<Game[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_games") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveGame(game: Game) : Promise<Result<Game, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_game", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteGame(gameId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_game", { gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectGamesFromBottles() : Promise<DetectedGame[]> {
    return await TAURI_INVOKE("detect_games_from_bottles");
},
async detectGamesForBottle(bottlePath: string) : Promise<Result<DetectedGame[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_games_for_bottle", { bottlePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runGameInstaller(installerPath: string, bottlePath: string, runtime: string) : Promise<Result<GameInstallerResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_game_installer", { installerPath, bottlePath, runtime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importGame(import_: GameImport) : Promise<Result<Game, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_game", { import: import_ }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectSteamGames() : Promise<SteamGame[]> {
    return await TAURI_INVOKE("detect_steam_games");
},
async detectEpicGames() : Promise<EpicGame[]> {
    return await TAURI_INVOKE("detect_epic_games");
},
async detectGogGames() : Promise<GogGame[]> {
    return await TAURI_INVOKE("detect_gog_games");
},
async listProfiles() : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProfiles(profiles: JsonValue[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_profiles", { profiles }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async migrateFromLocalStorage(profilesJson: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("migrate_from_local_storage", { profilesJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Info about a detected compatibility runtime.
 */
export type RuntimeInfo = { id: string; name: string; available: boolean; version: string | null; executable_path: string | null; error: string | null }
/**
 * Health status of a bottle / prefix.
 */
export type BottleHealth = "Good" | "Warning" | "Broken"
/**
 * Info about a detected or managed bottle / prefix.
 */
export type Bottle = { id: string; name: string; runtime: string; path: string; runtime_version: string | null; architecture: string | null; windows_version: string | null; installed_components: string[]; storage_bytes: number | null; notes: string | null; health: BottleHealth }
/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Result of running a launched/external process.
 */
export type ProcessOutcome = { stdout: string; stderr: string; exit_code: number | null }
/**
 * Stored log entry (mirrors the TypeScript `ProfileLogEntry`).
 */
export type ProfileLogEntry = { id: string; profileId: string; createdAt: string; command: string; stdout: string; stderr: string; exitCode: number | null }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
/**
 * How the game was imported into the library.
 */
export type GameImportSource = "Manual" | "AppBundle" | "ExeMsi" | "Installer" | "SteamLibrary" | "EpicLibrary" | "GogLibrary"
export type GameInstallerResult = { exitCode: number | null; stdout: string; stderr: string }
/**
 * A game entry in the library.
 */
export type Game = { id: string; title: string; importSource: GameImportSource; installPath: string | null; artworkPath: string | null; tags: string[]; notes: string | null; profileIds: string[]; extraArgs: string[]; createdAt: string; updatedAt: string }
/**
 * A game detected inside a bottle or prefix.
 */
export type DetectedGame = { name: string; exe_path: string; bottle_id: string; bottle_name: string; bottle_path: string; publisher: string | null; version: string | null }
/**
 * Data needed to import a new game into the library.
 */
export type GameImport = { title: string; importSource: GameImportSource; installPath: string | null; artworkPath: string | null; tags: string[]; notes: string | null; profileIds: string[]; extraArgs: string[] }
/**
 * A game found in a Steam library.
 */
export type SteamGame = { app_id: string; name: string; install_dir: string; size_on_disk: number | null }
/**
 * A game found via the Epic Games Launcher.
 */
export type EpicGame = { app_name: string; name: string; install_location: string; launch_executable: string | null }
/**
 * A game found via GOG Galaxy.
 */
export type GogGame = { game_id: string; name: string; install_dir: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
