use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        bottle, game, launcher, notifications, preferences, profile, provider, quick_pane,
        recovery, runtime,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        launcher::launch_profile_executable,
        launcher::run_build_step,
        launcher::save_log,
        launcher::read_logs,
        runtime::detect_runtimes,
        provider::build_runtime_launch_command,
        provider::validate_runtime_config,
        bottle::detect_bottles,
        bottle::get_bottle_meta,
        bottle::create_bottle,
        bottle::clone_bottle,
        bottle::repair_bottle,
        bottle::reset_bottle,
        bottle::export_bottle,
        bottle::import_bottle,
        bottle::save_bottle_notes,
        bottle::save_bottle_config,
        bottle::delete_bottle,
        bottle::detect_games_from_bottles,
        game::list_games,
        game::save_game,
        game::delete_game,
        game::import_game,
        game::detect_steam_games,
        game::detect_epic_games,
        game::detect_gog_games,
        game::run_game_installer,
        profile::list_profiles,
        profile::save_profiles,
        profile::migrate_from_local_storage,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
